### ISSUE TITLE
Deprecated Warnings

### ISSUE THREAD

**Issue by senften** [webextensions/copy-files-from-to#20]
Working from a new create-react app, I add copy-files-from-to and received the following warnings

> $ npm install copy-files-from-to --save-dev
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> 
> added 52 packages, and audited 1480 packages in 3s

I was wondering if there was plans to resolve these. The har-validator is the one that really caught my eye

**Comment by webextensions** [comment]
@senften 
Thank you for bringing it to notice.

Practically, for almost any general use-case, these warnings shouldn't matter because as per our guestimates, people are using it only for dev/build purposes and not using it with insecure input.

But, anyways, to keep it simple for the developers to adopt this library, appropriate changes/updates should be made to reduce/remove such warnings.

For fixing the issue:
* PRs are welcome
* Otherwise, when we are able to spend a bit more time on it, we shall update all possible dependencies (hopefully in coming months)

Keeping this issue in Open state for future revisit.

**Comment by webextensions** [comment]
@senften 
The issue has been fixed with https://github.com/webextensions/copy-files-from-to/commit/eae87d1181105f196578f6e54687b15e2c3398ea which is available on npm with copy-files-from-to@3.5.0 onwards :+1:
