### ISSUE TITLE
Quiet/Silent mode for CI

### ISSUE THREAD

**Issue by joelpittet** [webextensions/copy-files-from-to#23]
I've been using this tool for some time now, it is simple and great!

### Problem/Motivation:
We have a monthly process of checking and updating various packages and with some packages that can mean a lot of files (like fontawesome or ckeditor) to copy over, which tends to flood the screen. The actual diff in git at the moment would suffice our review of the changes.

### Proposed Solution
Add a `-q` option flag to quiet the output for CI and scripts.

Thank you for considering this and keep up the great work!

**Comment by webextensions** [comment]
@joelpittet 

Thank you for the feedback :smile:

This issue has been fixed with https://github.com/webextensions/copy-files-from-to/commit/8a136e7a90f84995a1fbafdd6c1eb81ba71d1a6e and this feature is now available with `copy-files-from-to@3.9.0` via `--silent` parameter which leads to `Reduced logging (log only warnings and errors)`

Marking resolved :+1:
