### ISSUE TITLE
Expose Terser options

### ISSUE THREAD

**Issue by atl-mk** [webextensions/copy-files-from-to#26]
Could do something like
```json
    "copyFilesSettings": {
        "terserOptions": {
        }
    }
```

This could keep `copy-files-from-to` relatively agnostic of all the Terser stuff below it. Any breaking change to it would be pretty limited to maybe switching from terser to whatever the thing is that replaces it.

I like that copy-files-from-to provides a nicer API for what the main purpose. It would be nice to tweak just a couple of small things like sourcemap generation or ecma script minification target

**Comment by webextensions** [comment]
@atl-mk 
Fixed with https://github.com/webextensions/copy-files-from-to/commit/a8f1b0a9270ca4e334b870f2dc4b0b3e73821140 :+1: 

Example usage:
```
    "copyFilesSettings": {
        "minifyJs": true,
        "minifyJsTerserOptions": {
            "mangle": false
        }
    }
```

For more details, the documentation is added at README.md (https://github.com/webextensions/copy-files-from-to/blob/main/README.md#structure-of-copyfiles-instruction-file)
