### ISSUE TITLE
Readme not up to date

### ISSUE THREAD

**Issue by kuhnroyal** [webextensions/copy-files-from-to#5]
It is not working without adding the files array to `filesToCopy` and at least have an empty `settings` object.

```
{
  "filesToCopy": [
    {
      "from": "../../README.md",
      "to": "../../dist/README.md"
    }
  ],
  "settings": {}
}
```

Otherwise there are several errors:
```
    if (settings.addLinkToSourceOfOrigin) {
                 ^

TypeError: Cannot read property 'addLinkToSourceOfOrigin' of undefined
    at writeContents (/foo/node_modules/copy-files-from-to/index.js:158:18)
```
```
filesToCopy = filesToCopy.map(function (fileToCopy) {
                          ^

TypeError: Cannot read property 'map' of undefined
    at Object.<anonymous> (/foo/node_modules/copy-files-from-to/index.js:79:27)

```

**Comment by webextensions** [comment]
This issue has been fixed with https://github.com/webextensions/copy-files-from-to/commit/b21d8b21bf97bbb229329cac2e3911d26fd495a1

The update has been published at https://www.npmjs.com/package/copy-files-from-to

Now, the README.md file is elaborate and gives proper examples (basic as well as advanced).
**Please note that some parts of the file's data structure have been changed.**
